config/routes.rb
Rails.application.routes.draw do
resources :posts

get 'about' => 'welcome#about'

  root to: 'welcome#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  	@posts = Post.all
  end

  def show
  	@post = Post.find(params[:id])
  end

  def new
  end

  def edit
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bloccit</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container">
		<ul class="nav nav-tabs">
			<li><%= link_to "Bloccit", root_path %></li>
			<li><%= link_to "About", about_path %></li>			
		</ul>

<%= yield %>
	<div>

</body>
</html>

app/views/posts/edit.html.erb
<h1>All Posts</h1>
<% @posts.each do |post| %>
	<p><%= link_to post.title, post_path(post.id) %></p>
<% end %>

app/views/posts/index.html.erb
<h1>All Posts</h1>
<% @posts.each do |post| %>
	<div class="media">
		<div class="media-body">
			<h4 class="media-heading">
				<%= link_to post.title, post %>
			</h4>
		</div>
	</div>
<% end %>

app/views/posts/new.html.erb
<h1>Posts#new</h1>
<p>Find me in app/views/posts/new.html.erb</p>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p><%= @post.body %></p>

app/views/welcome/about.html.erb
<h1>About Bloccit</h1>
<p>Create by: Baron jon</p>

app/views/welcome/contact.html.erb
<h1>Welcome#contact</h1>
<p>Find me in app/views/welcome/contact.html.erb</p>

app/views/welcome/index.html.erb
<h1>Welcome to Bloccit</h1>
<p>This is the home page for Bloccit.</p>